domain_path: C:\Users\akaly\workplace2\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinix2\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
